# Generated by Django 5.2.11 on 2026-02-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('reddit', 'Reddit'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('other', 'Other')], max_length=50)),
                ('profile_url', models.URLField(unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('keyword', models.TextField(blank=True, help_text='Palavras-chave extraídas do perfil')),
                ('relevance_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
